Add classes feature
Mar12358/school-library-people pull request #1
Opened 2023-07-26 20:13 UTC by Mar12358

# Added Features

- Follow best practices for Ruby

- Create class `Person` with  the following:
  - Instance vars: `@id`, `@name`, and `@age`.
  - Constructor with `name`,  `age`, and `parent_permission` as parameter. `name` and `parent_permission` are optional and have default values of `"Unknown"` and `true`.
  - Getters for `@id`, `@name`, and `@age`.
  - Setters for `@name` and `@age`.
  - Private method `of_age?` that returns `true` if `@age` is greater or equal to 18 and `false` otherwise.
  - Public method `can_use_services?` that returns `true` if person is of age or if they have permission from parents.
- Create class `Student` with the following:
  - Inherits from `Person`.
  - Constructor extends parent's constructor by adding `@classroom` and a parameter for it.
  - Method `play_hooky` that returns `"¯\(ツ)/¯"`.
- Create class `Teacher` with the following:
  - Inherits from `Person`.
  - Constructor extends parent's constructor by adding `@specialization` and a parameter for it.
  - Override `can_use_services?` so it always returns `true`.
- Each class should be saved in a separate file.

2023-07-26 20:26 UTC, frank1738 reviewed
Hi @Mar12358 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] Kindly fill your readme file with the relevant project details for professional documentation purposes

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-07-27 16:59 UTC, Shedrack-Sunday requested changes
Hello @Mar12358         👋 

# CHANGES REQUIRED ♻️

Impressive work on the project so far👏
You've done extremely well so far in this project,  However, there are some adjustments you need to make to move to the next project. 💯

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights   
- Good use of GitHub features ✔️   
- Nice work with the ruby syntax✔️ 
   
 
  
# Required Changes  🌵  

- [ ] You've done well, However, kindly check some key point note I pointed out to meet the requirements before moving to the next project 👍 

_Check the comments for a detailed review 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing really improves your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-07-27 16:59 UTC, Shedrack-Sunday commented on person.rb
> +  def initialize(name, age, _parent_permission)
- [ ] Based on the requirements,   `name` and `parent_permission` should have default values of "Unknown" and `true.`. Kindly make the appropriate changes 👍 

### Requirements:
![image](https://github.com/Mar12358/school-library-people/assets/50990925/008b968c-694d-4eb8-a0a2-54c6556f6598)

2023-07-27 16:59 UTC, Shedrack-Sunday commented on student.rb
> +  end
- [ ] In this section, you called the `super` with arguments, yet, there are no parameters i the `initialize` method above. 
- [ ] The problem here is that these three variables `(name, age, and parent_permission)` are not defined within the initialize method or as parameters of the Student class, so calling `super(name, age, parent_permission)` will result in an error. This [content](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/class_and_object_for_irb.md#constructor-and-instance-vars) will help to revise 👍

2023-07-27 16:59 UTC, Shedrack-Sunday commented on teacher.rb
> +
- [ ] As stated in the requirements, this class should inherit from the `Person` class. Kindly take note of my comments in the `students` class file when inheriting with parameers 👍 

### Instructions:
![image](https://github.com/Mar12358/school-library-people/assets/50990925/77356e42-2694-47df-afa9-6819fbf00250)

2023-07-27 18:33 UTC, sumairq approved these changes
### Hi @Mar12358 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ good job implementing changes
✔️Linters are passing
✔️Very professional README
✔️Correct Git flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-27 18:39 UTC, merged